services:
  bookdb:
    image: postgres:latest
    container_name: bookdb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
#    networks:
#      - airbyte_airbyte_internal
#      - airbyte_airbyte_public
#      - airbyte_default
#      - bkstore_network

  observability:
    image: metabase/metabase
    container_name: observability
    ports:
      - "3000:3000"
    volumes:
      - ./metabase_data:/var/lib/metabase
    depends_on:
      - bookdb

#networks:
#  airbyte_airbyte_public:
#    external: true
#  airbyte_airbyte_internal:
#    external: true
#  bkstore_network:
#    driver: bridge
